#!/bin/bash
#
# * jUpgrade
# *
# * @author      Matias Aguirre
# * @email       maguirre@matware.com.ar
# * @url         http://www.matware.com.ar
# * @license     GNU/GPL
# 

PROJECT="jupgrade"
VERSION="0.5.1"

# Initial Cleanup
rm com_${PROJECT}-${VERSION}.zip
rm -rf com_${PROJECT}/
rm -rf ${PROJECT}-${VERSION}
rm -rf com_${PROJECT}-latest.zip

cp -r ../trunk ${PROJECT}-${VERSION}

mtwRemoveSVNFiles ${PROJECT}-${VERSION}

mv ${PROJECT}-${VERSION}-without-svn/ com_${PROJECT}

#rm com_${PROJECT}/admin/extensions/*.gz
rm com_${PROJECT}/admin/${PROJECT}_config.php
rm com_${PROJECT}/admin/${PROJECT}.xml

zip -r com_${PROJECT}-${VERSION}.zip com_${PROJECT}/

# Finish Cleanup
rm -rf com_${PROJECT}/
rm -rf ${PROJECT}-${VERSION}
rm -rf com_${PROJECT}-latest.zip

ln -s com_${PROJECT}-${VERSION}.zip com_${PROJECT}-latest.zip
